# Fetch full history + tags so manual runs can find the latest tag.
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      tags: true   # needed to discover the "last tag" on manual runs

steps:
  # ---------- DEV IMAGE (ferris-store:dev) ----------
  docker-build-dev:
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      # Publish to GHCR
      registry: ghcr.io
      repo: ghcr.io/${CI_REPO_OWNER}/Ferris-Store
      tags: dev
      dockerfile: Dockerfile
      # Build in dev profile, Alpine final image
      build_args:
        PROFILE: dev
      # Link image to the source repository (OCI label)
      labels:
        - org.opencontainers.image.source=https://github.com/${CI_REPO}
      # Also add the plugin's default git-derived labels (version, revision, etc.)
      default_labels: true
      # GHCR auth
      username:
        from_secret: GHCR_USERNAME
      password:
        from_secret: GHCR_TOKEN
    when:
      # Build on pushes to the development branch…
      - event: push
        branch: development
      # …and also when run manually.
      - event: manual

  # ---------- DISCOVER RELEASE TAG ----------
  compute-release-tag:
    image: alpine:latest
    commands:
      - set -e
      # If this is a tag event, use that tag; otherwise, grab the latest tag.
      - |
        if [ "$CI_PIPELINE_EVENT" = "tag" ] && [ -n "$CI_COMMIT_TAG" ]; then
          TAG="$CI_COMMIT_TAG"
        else
          git fetch --tags --force
          TAG="$(git describe --tags --abbrev=0)"
        fi
        echo "$TAG" > .release_tag
        # Let the docker-buildx plugin read tags from a file
        printf "%s\n%s\n" "$TAG" "latest" > .tags
    when:
      - event: tag
      - event: manual

  # ---------- RELEASE IMAGE (ferris-store:<tag> and :latest) ----------
  docker-build-release:
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    depends_on: [compute-release-tag]
    settings:
      registry: ghcr.io
      repo: ghcr.io/${CI_REPO_OWNER}/ferris-store
      tags_file: .tags
      dockerfile: Dockerfile
      build_args:
        PROFILE: release
      labels:
        - org.opencontainers.image.source=https://github.com/${CI_REPO}
      default_labels: true
      username:
        from_secret: GHCR_USERNAME
      password:
        from_secret: GHCR_TOKEN
    when:
      - event: tag
      - event: manual
