[package]
name = "market"
version = "0.1.0"
edition = "2021"
authors = ["Federico Frigerio"]

[dependencies]
actix-web = "4.8.0"
env_logger = "0.11.3"
figment = { version = "0.10.19", features = ["env", "toml"] }
lazy_static = "1.5.0"
log = "0.4.21"
sea-orm = { version = "1.0.1", features = ["sqlx-mysql", "runtime-tokio-rustls", "macros"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"

[workspace]
members = [".", "entity", "migration"]