[package]
name = "market"
version = "0.1.0"
edition = "2021"
authors = ["Federico Frigerio"]

[dependencies]
actix-web = "4.8.0"
figment = { version = "0.10.19", features = ["env", "toml"] }
lazy_static = "1.5.0"
sea-orm = { version = "1.0.1", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "chrono"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.40.0", features = ["full"] }
entity = { path = "entity" }
migration = { path = "migration" }
derive-new = "0.7.0"
repository_macro = { path = "./repository_macro" }
jsonwebtoken = "9.3.0"

[workspace]
members = [".", "entity", "migration", "repository_macro"]
