[package]
name = "ferris-store"
version = "0.1.0"
edition = "2021"
authors = ["Federico Frigerio"]

[dependencies]
actix-web = "4.11.0"
figment = { version = "0.10.19", features = ["env", "toml"] }
sea-orm = { version = "1.1.12", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "chrono"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
entity = { path = "entity" }
migration = { path = "migration" }
derive-new = "0.7.0"
repository_macro = { path = "./repository_macro" }
jsonwebtoken = "9.3.1"
chrono = "0.4.41"
futures-util = "0.3.31"
password-auth = "1.0.0"
derive-getters = { version = "0.5.0", features = ["auto_copy_getters"] }
utoipa = { version = "5.4.0", features = ["actix_extras", "chrono", "macros"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["actix-web"] }
log = { version = "0.4.27", features = ["std"] }
num_enum = "0.7.3"
tokio = "1.45.1"
mongodb = "3.2.3"

[workspace]
members = [".", "entity", "migration", "repository_macro"]
