[package]
name = "ferris-store"
version = "0.1.0"
edition = "2021"
authors = ["Federico Frigerio"]

[dependencies]
actix-web = "4.10.2"
figment = { version = "0.10.19", features = ["env", "toml"] }
sea-orm = { version = "1.1.7", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "chrono"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
entity = { path = "entity" }
migration = { path = "migration" }
derive-new = "0.7.0"
repository_macro = { path = "./repository_macro" }
jsonwebtoken = "9.3.1"
chrono = "0.4.40"
futures-util = "0.3.31"
password-auth = "1.0.0"
derive-getters = { version = "0.5.0", features = ["auto_copy_getters"] }
env_logger = "0.11.7"
utoipa = { version = "5.3.1", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web"] }
rand = "0.9.0"
log = "0.4.26"

[workspace]
members = [".", "entity", "migration", "repository_macro"]
