address = "127.0.0.1"
port = 8080
workers = 4
db_url = "postgres://postgres:password@localhost"
jwt_secret = "jwt_super_secret"
jwt_validity_days = 7
logs_mongo_uri = "mongodb://localhost:27017"
logs_db_name = "logs"
default_admin_password = "password"
default_admin_email = "root"
allowed_signup_domains = ["studenti.unitn.it"]

smtp_host = "localhost"
smtp_port = 1025
smtp_username = "user@locahost"
smtp_password = "password"
email_from = "Advanced Programming"
email_token_secret = "secret_token"
frontend_base_url = "http://localhost:3000"
skip_email_confirmation = false