services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=market
      - POSTGRES_PASSWORD=market
      - POSTGRES_DB=market
      - TZ=Europe/rome
    network_mode: host
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: "unless-stopped"

  otel-lgtm:
    image: grafana/otel-lgtm
    container_name: otel
    environment:
      - TZ=Europe/rome
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - otel_data:/data
    restart: "unless-stopped"

volumes:
  db_data:
  otel_data:
