[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Federico Frigerio"]

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = "1.1.13"
serde = { version = "1.0.219", features = ["derive"] }
utoipa = "5.4.0"
