//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "blacklist")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub blacklist_id: i32,
    #[sea_orm(unique)]
    pub university_id: i32,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub fist_name: String,
    pub last_name: String,
    pub banned_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
