//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "complaints")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub from_group_id: i64,
    pub to_group_id: i64,
    #[sea_orm(column_type = "Text")]
    pub complain_text: String,
    pub date_of_creation: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::groups::Entity",
        from = "Column::FromGroupId",
        to = "super::groups::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Groups2,
    #[sea_orm(
        belongs_to = "super::groups::Entity",
        from = "Column::ToGroupId",
        to = "super::groups::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Groups1,
}

impl ActiveModelBehavior for ActiveModel {}
