//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "group_parts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub group_part_id: i32,
    pub project_id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::group_parts_components::Entity")]
    GroupPartsComponents,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::ProjectId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Projects,
}

impl Related<super::group_parts_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupPartsComponents.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::group_components::Entity> for Entity {
    fn to() -> RelationDef {
        super::group_parts_components::Relation::GroupComponents.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::group_parts_components::Relation::GroupParts
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
