//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "groups_and_project_components")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub group_id: i32,
    pub component_id: i32,
    pub custom_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub mark_down_description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub code_link: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub telegram_support_link: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fair_purchasing::Entity")]
    FairPurchasing,
    #[sea_orm(
        belongs_to = "super::groups::Entity",
        from = "Column::GroupId",
        to = "super::groups::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Groups,
    #[sea_orm(
        belongs_to = "super::project_components::Entity",
        from = "Column::ComponentId",
        to = "super::project_components::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ProjectComponents,
}

impl Related<super::fair_purchasing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FairPurchasing.def()
    }
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Groups.def()
    }
}

impl Related<super::project_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectComponents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
