//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "groups")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub option_id: i64,
    pub project_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::groups_and_project_components::Entity")]
    GroupsAndProjectComponents,
    #[sea_orm(
        belongs_to = "super::project_options::Entity",
        from = "Column::OptionId",
        to = "super::project_options::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ProjectOptions,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Projects,
    #[sea_orm(has_many = "super::security_codes::Entity")]
    SecurityCodes,
    #[sea_orm(has_many = "super::students_and_groups::Entity")]
    StudentsAndGroups,
}

impl Related<super::groups_and_project_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupsAndProjectComponents.def()
    }
}

impl Related<super::project_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectOptions.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::security_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SecurityCodes.def()
    }
}

impl Related<super::students_and_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentsAndGroups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
