//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "group_parts_components")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub group_component_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub group_part_id: i32,
    pub quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::group_components::Entity",
        from = "Column::GroupComponentId",
        to = "super::group_components::Column::GroupComponentId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GroupComponents,
    #[sea_orm(
        belongs_to = "super::group_parts::Entity",
        from = "Column::GroupPartId",
        to = "super::group_parts::Column::GroupPartId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GroupParts,
}

impl Related<super::group_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupComponents.def()
    }
}

impl Related<super::group_parts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupParts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
