//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod admin_roles;
pub mod admins;
pub mod blacklist;
pub mod complaints;
pub mod fairs;
pub mod group_components;
pub mod group_members;
pub mod group_part_selections;
pub mod group_parts;
pub mod group_parts_components;
pub mod groups;
pub mod projects;
pub mod security_codes;
pub mod student_part_selections;
pub mod student_parts;
pub mod student_parts_components;
pub mod student_roles;
pub mod student_uploads;
pub mod students;
pub mod students_components;
pub mod transactions;
