//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod complaints;
pub mod courses;
pub mod groups;
pub mod groups_and_project_components;
pub mod individual_work_options;
pub mod options_components_and_quantity;
pub mod project_components;
pub mod project_options;
pub mod projects;
pub mod roles;
pub mod roles_hierarchy;
pub mod security_codes;
pub mod students_and_groups;
pub mod students_individual_work;
pub mod users;
pub mod users_projects_roles;
