//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod auxiliary_roles;
pub mod black_list;
pub mod complaints;
pub mod fair;
pub mod fair_purchasing;
pub mod groups;
pub mod groups_and_project_components;
pub mod individual_work_options;
pub mod options_components_and_quantity;
pub mod project_components;
pub mod project_options;
pub mod projects;
pub mod roles;
pub mod security_codes;
pub mod students_and_groups;
pub mod students_and_individual_work;
pub mod users;
pub mod users_projects_and_roles;
