//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::admins::Entity as Admins;
pub use super::auxiliary_roles::Entity as AuxiliaryRoles;
pub use super::black_list::Entity as BlackList;
pub use super::complaints::Entity as Complaints;
pub use super::fairs::Entity as Fairs;
pub use super::fairs_purchasing::Entity as FairsPurchasing;
pub use super::groups::Entity as Groups;
pub use super::groups_and_project_components::Entity as GroupsAndProjectComponents;
pub use super::individual_work_options::Entity as IndividualWorkOptions;
pub use super::options_components_and_quantity::Entity as OptionsComponentsAndQuantity;
pub use super::project_components::Entity as ProjectComponents;
pub use super::project_options::Entity as ProjectOptions;
pub use super::projects::Entity as Projects;
pub use super::roles::Entity as Roles;
pub use super::security_codes::Entity as SecurityCodes;
pub use super::settings::Entity as Settings;
pub use super::students_and_groups::Entity as StudentsAndGroups;
pub use super::students_and_individual_work::Entity as StudentsAndIndividualWork;
pub use super::users::Entity as Users;
pub use super::users_projects_and_roles::Entity as UsersProjectsAndRoles;
