//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "project_components")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub project_id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::groups_and_project_components::Entity")]
    GroupsAndProjectComponents,
    #[sea_orm(has_many = "super::options_components_and_quantity::Entity")]
    OptionsComponentsAndQuantity,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Projects,
}

impl Related<super::groups_and_project_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupsAndProjectComponents.def()
    }
}

impl Related<super::options_components_and_quantity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OptionsComponentsAndQuantity.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
