//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "roles_hierarchy")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub role_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub parent_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(belongs_to = "super::roles::Entity", from = "Column::ParentId", to = "super::roles::Column::Id", on_update = "NoAction", on_delete = "SetDefault")]
    Roles2,
    #[sea_orm(belongs_to = "super::roles::Entity", from = "Column::RoleId", to = "super::roles::Column::Id", on_update = "NoAction", on_delete = "Cascade")]
    Roles1,
}

impl ActiveModelBehavior for ActiveModel {}
