//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub is_auxiliary: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::security_codes::Entity")]
    SecurityCodes,
    #[sea_orm(has_many = "super::users_projects_roles::Entity")]
    UsersProjectsRoles,
}

impl Related<super::security_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SecurityCodes.def()
    }
}

impl Related<super::users_projects_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersProjectsRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
