//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "security_codes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub security_code_id: i32,
    pub project_id: i32,
    pub student_role_id: i32,
    #[sea_orm(unique)]
    pub code: String,
    pub expiration: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::ProjectId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::student_roles::Entity",
        from = "Column::StudentRoleId",
        to = "super::student_roles::Column::StudentRoleId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StudentRoles,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::student_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
