//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa::ToSchema,
)]
#[sea_orm(table_name = "students")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub student_id: i32,
    pub first_name: String,
    pub last_name: String,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub university_id: i32,
    pub password_hash: String,
    pub student_role_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::group_members::Entity")]
    GroupMembers,
    #[sea_orm(has_many = "super::student_part_selections::Entity")]
    StudentPartSelections,
    #[sea_orm(
        belongs_to = "super::student_roles::Entity",
        from = "Column::StudentRoleId",
        to = "super::student_roles::Column::StudentRoleId",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    StudentRoles,
}

impl Related<super::group_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupMembers.def()
    }
}

impl Related<super::student_part_selections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentPartSelections.def()
    }
}

impl Related<super::student_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
