//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "student_parts_components")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub student_part_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub students_component_id: i32,
    pub quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::student_parts::Entity",
        from = "Column::StudentPartId",
        to = "super::student_parts::Column::StudentPartId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StudentParts,
    #[sea_orm(
        belongs_to = "super::students_components::Entity",
        from = "Column::StudentsComponentId",
        to = "super::students_components::Column::StudentsComponentId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StudentsComponents,
}

impl Related<super::student_parts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentParts.def()
    }
}

impl Related<super::students_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentsComponents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
