//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "students_components")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub students_component_id: i32,
    pub project_id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::ProjectId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Projects,
    #[sea_orm(has_many = "super::student_parts_components::Entity")]
    StudentPartsComponents,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::student_parts_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudentPartsComponents.def()
    }
}

impl Related<super::student_parts::Entity> for Entity {
    fn to() -> RelationDef {
        super::student_parts_components::Relation::StudentParts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::student_parts_components::Relation::StudentsComponents
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
