//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub transaction_id: i32,
    pub buyer_group_id: i32,
    pub group_part_selection_id: i32,
    pub fair_id: i32,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fairs::Entity",
        from = "Column::FairId",
        to = "super::fairs::Column::FairId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Fairs,
    #[sea_orm(
        belongs_to = "super::group_part_selections::Entity",
        from = "Column::GroupPartSelectionId",
        to = "super::group_part_selections::Column::GroupPartSelectionId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GroupPartSelections,
    #[sea_orm(
        belongs_to = "super::groups::Entity",
        from = "Column::BuyerGroupId",
        to = "super::groups::Column::GroupId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Groups,
}

impl Related<super::fairs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fairs.def()
    }
}

impl Related<super::group_part_selections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupPartSelections.def()
    }
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Groups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
